version: "3.9"

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgresdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.19
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 8081:80

volumes:
  postgresdata:
